In [4]:
import pandas as pd
from clean_region_names import replacing

In [2]:
df_Subject_Scores = pd.read_csv("Fənlər_üzrə_nisbi_balların_dinamikası.csv")

In [3]:
df_Subject_Scores.head()

,İl,Bölgə,Məktəb,Fənn,Cins,Düzgün cavabların faizi,Reytinq,Buraxılış_imtahanları
0,2012,Bakı Ş. Yasamal Rayonu,13 saylı orta məktəb,Ana dili,oğlanlar,47.62,0.996,tam orta təhsil səviyyəsi
1,2013,Bakı Ş. Yasamal Rayonu,13 saylı orta məktəb,Ana dili,oğlanlar,47.28,1.015,tam orta təhsil səviyyəsi
2,2014,Bakı Ş. Yasamal Rayonu,13 saylı orta məktəb,Ana dili,oğlanlar,55.65,1.109,tam orta təhsil səviyyəsi
3,2015,Bakı Ş. Yasamal Rayonu,13 saylı orta məktəb,Ana dili,oğlanlar,43.64,0.923,tam orta təhsil səviyyəsi
4,2016,Bakı Ş. Yasamal Rayonu,13 saylı orta məktəb,Ana dili,oğlanlar,58.43,1.171,tam orta təhsil səviyyəsi

In [5]:
df_Subject_Scores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1041177 entries, 0 to 1041176
Data columns (total 8 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   İl                       1041177 non-null  int64
 1   Bölgə                    1041177 non-null  object
 2   Məktəb                   1041177 non-null  object
 3   Fənn                     1038618 non-null  object
 4   Cins                     1041177 non-null  object
 5   Düzgün cavabların faizi  778060 non-null   float64
 6   Reytinq                  778060 non-null   float64
 7   Buraxılış_imtahanları    1041177 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 63.5+ MB

In [6]:
replacing(df_Subject_Scores, "Bölgə")

,İl,Bölgə,Məktəb,Fənn,Cins,Düzgün cavabların faizi,Reytinq,Buraxılış_imtahanları
0,2012,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,oğlanlar,47.62,0.996,tam orta təhsil səviyyəsi
1,2013,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,oğlanlar,47.28,1.015,tam orta təhsil səviyyəsi
2,2014,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,oğlanlar,55.65,1.109,tam orta təhsil səviyyəsi
3,2015,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,oğlanlar,43.64,0.923,tam orta təhsil səviyyəsi
4,2016,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,oğlanlar,58.43,1.171,tam orta təhsil səviyyəsi
...,...,...,...,...,...,...,...,...
1041172,2020,siyəzən rayonu,6 saylı şəhər orta məktəbi,Azərbaycan dili (dövlət dili),bütövlükdə,50.28,0.922,ümumi orta təhsil səviyyəsi
1041173,2021,siyəzən rayonu,6 saylı şəhər orta məktəbi,Azərbaycan dili (dövlət dili),bütövlükdə,64.83,1.217,ümumi orta təhsil səviyyəsi
1041174,2022,siyəzən rayonu,6 saylı şəhər orta məktəbi,Azərbaycan dili (dövlət dili),bütövlükdə,60.00,1.027,ümumi orta təhsil səviyyəsi
1041175,2023,siyəzən rayonu,6 saylı şəhər orta məktəbi,Azərbaycan dili (dövlət dili),bütövlükdə,54.64,1.058,ümumi orta təhsil səviyyəsi
1041176,2024,siyəzən rayonu,6 saylı şəhər orta məktəbi,Azərbaycan dili (dövlət dili),bütövlükdə,56.64,1.072,ümumi orta təhsil səviyyəsi

In [15]:
df_Subject_Scores.isnull().sum()

İl                              0
Bölgə                           0
Məktəb                          0
Fənn                         2559
Cins                            0
Düzgün cavabların faizi    263117
Reytinq                    263117
Buraxılış_imtahanları           0
dtype: int64

In [ ]:
df_Subject_Scores[df_Subject_Scores['Fənn'].isna()]

,İl,Bölgə,Məktəb,Fənn,Cins,Düzgün cavabların faizi,Reytinq,Buraxılış_imtahanları
5265,2012,bakı şəhəri yasamal rayonu,172 saylı orta məktəb,NaN,oğlanlar,48.33,1.011,tam orta təhsil səviyyəsi
5266,2013,bakı şəhəri yasamal rayonu,172 saylı orta məktəb,NaN,oğlanlar,40.78,0.875,tam orta təhsil səviyyəsi
5267,2014,bakı şəhəri yasamal rayonu,172 saylı orta məktəb,NaN,oğlanlar,37.14,0.740,tam orta təhsil səviyyəsi
5268,2015,bakı şəhəri yasamal rayonu,172 saylı orta məktəb,NaN,oğlanlar,NaN,NaN,tam orta təhsil səviyyəsi
5269,2016,bakı şəhəri yasamal rayonu,172 saylı orta məktəb,NaN,oğlanlar,NaN,NaN,tam orta təhsil səviyyəsi
...,...,...,...,...,...,...,...,...
1019917,2020,xaçmaz rayonu,Suxtakələ kənd orta məktəbi,NaN,bütövlükdə,NaN,NaN,tam orta təhsil səviyyəsi
1019918,2021,xaçmaz rayonu,Suxtakələ kənd orta məktəbi,NaN,bütövlükdə,NaN,NaN,tam orta təhsil səviyyəsi
1019919,2022,xaçmaz rayonu,Suxtakələ kənd orta məktəbi,NaN,bütövlükdə,NaN,NaN,tam orta təhsil səviyyəsi
1019920,2023,xaçmaz rayonu,Suxtakələ kənd orta məktəbi,NaN,bütövlükdə,NaN,NaN,tam orta təhsil səviyyəsi
1019921,2024,xaçmaz rayonu,Suxtakələ kənd orta məktəbi,NaN,bütövlükdə,NaN,NaN,tam orta təhsil səviyyəsi

In [23]:
# Məlumat mənbəsində bu müşahidələr üzrə performans göstəriciləri mövcud deyil.
# Subyektiv və ya fərziyyəyə əsaslanan doldurma analitik nəticələrin düzgünlüyünə
# mənfi təsir göstərə biləcəyi üçün bu sətrləri silirəm.
df_Subject_Scores.dropna(subset=('Fənn', 'Düzgün cavabların faizi', 'Reytinq'), inplace=True)

In [26]:
df_Subject_Scores.info()

<class 'pandas.core.frame.DataFrame'>
Index: 777361 entries, 0 to 1041176
Data columns (total 8 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   İl                       777361 non-null  int64
 1   Bölgə                    777361 non-null  object
 2   Məktəb                   777361 non-null  object
 3   Fənn                     777361 non-null  object
 4   Cins                     777361 non-null  object
 5   Düzgün cavabların faizi  777361 non-null  float64
 6   Reytinq                  777361 non-null  float64
 7   Buraxılış_imtahanları    777361 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 53.4+ MB

In [27]:
df_Subject_Scores.to_csv("Fənlər_üzrə_nisbi_balların_dinamikası_cleaned.csv", index=False, encoding="utf-8-sig")